const Actions = {
    INIT_CUSTOMERS: 'INIT_CUSTOMERS',
    INIT_PRODUCTS:'INIT_PRODUCTS',
    INIT_PURCHES: 'INIT_PURCHES',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
}
export default Actions